version: '3.3'

networks:
  net:
    driver: overlay

services:
  zoo1:
    #image: gcr.io/abra-stock/zookeeper-stack:2.3.0
    image: cquan808/zookeeper-stack:2.3.0
    hostname: zoo1
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
      - target: 2888
        published: 2888
        protocol: tcp
        mode: host
      - target: 3888
        protocol: tcp
        mode: host
    networks:
      - net
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      # server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

#  zoo2:
#    image: zookeeper
#    hostname: zoo2
#    ports:
#      - 2182:2181
#    networks:
#      - net
#    environment:
#      ZOO_MY_ID: 2
#      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

#  zoo3:
#    image: zookeeper
#    hostname: zoo3
#    ports:
#      - 2183:2181
#    networks:
#      - net
#    environment:
#      ZOO_MY_ID: 3
#      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888      
